docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/facebook/react-native.git git@github.com:project-draco-hr/react-native.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/elastic/elasticsearch.git git@github.com:project-draco-hr/elasticsearch.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/google/guava.git git@github.com:project-draco-hr/guava.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/zxing/zxing.git git@github.com:project-draco-hr/zxing.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/spring-projects/spring-framework.git git@github.com:project-draco-hr/spring-framework.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/libgdx/libgdx.git git@github.com:project-draco-hr/libgdx.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/afollestad/material-dialogs.git git@github.com:project-draco-hr/material-dialogs.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/JetBrains/kotlin.git git@github.com:project-draco-hr/kotlin.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/eclipse/vert.x.git git@github.com:project-draco-hr/vert.x.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/prestodb/presto.git git@github.com:project-draco-hr/presto.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/android/platform_frameworks_base.git git@github.com:project-draco-hr/platform_frameworks_base.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/bazelbuild/bazel.git git@github.com:project-draco-hr/bazel.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/deeplearning4j/deeplearning4j.git git@github.com:project-draco-hr/deeplearning4j.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/gradle/gradle.git git@github.com:project-draco-hr/gradle.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/OpenRefine/OpenRefine.git git@github.com:project-draco-hr/OpenRefine.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/claritylab/lucida.git git@github.com:project-draco-hr/lucida.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/druid-io/druid.git git@github.com:project-draco-hr/druid.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/apache/storm.git git@github.com:project-draco-hr/storm.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/JetBrains/intellij-community.git git@github.com:project-draco-hr/intellij-community.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/yixia/VitamioBundle.git git@github.com:project-draco-hr/VitamioBundle.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/commonsguy/cw-omnibus.git git@github.com:project-draco-hr/cw-omnibus.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/mockito/mockito.git git@github.com:project-draco-hr/mockito.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/facebook/buck.git git@github.com:project-draco-hr/buck.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/openhab/openhab.git git@github.com:project-draco-hr/openhab.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/neo4j/neo4j.git git@github.com:project-draco-hr/neo4j.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/apache/cassandra.git git@github.com:project-draco-hr/cassandra.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/processing/processing.git git@github.com:project-draco-hr/processing.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/stephanenicolas/robospice.git git@github.com:project-draco-hr/robospice.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/actorapp/actor-platform.git git@github.com:project-draco-hr/actor-platform.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/dropbox/hackpad.git git@github.com:project-draco-hr/hackpad.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/haifengl/smile.git git@github.com:project-draco-hr/smile.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/Atmosphere/atmosphere.git git@github.com:project-draco-hr/atmosphere.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/google/closure-compiler.git git@github.com:project-draco-hr/closure-compiler.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/orientechnologies/orientdb.git git@github.com:project-draco-hr/orientdb.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/gocd/gocd.git git@github.com:project-draco-hr/gocd.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/java-native-access/jna.git git@github.com:project-draco-hr/jna.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/qii/weiciyuan.git git@github.com:project-draco-hr/weiciyuan.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/alibaba/jstorm.git git@github.com:project-draco-hr/jstorm.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/twitter/heron.git git@github.com:project-draco-hr/heron.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/apache/hadoop.git git@github.com:project-draco-hr/hadoop.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/stanfordnlp/CoreNLP.git git@github.com:project-draco-hr/CoreNLP.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/pedrovgs/DraggablePanel.git git@github.com:project-draco-hr/DraggablePanel.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/NLPchina/ansj_seg.git git@github.com:project-draco-hr/ansj_seg.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector.git git@github.com:project-draco-hr/Android-IMSI-Catcher-Detector.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/naver/pinpoint.git git@github.com:project-draco-hr/pinpoint.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/lipangit/JieCaoVideoPlayer.git git@github.com:project-draco-hr/JieCaoVideoPlayer.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/h2oai/h2o-2.git git@github.com:project-draco-hr/h2o-2.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/hibernate/hibernate-orm.git git@github.com:project-draco-hr/hibernate-orm.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/apache/zeppelin.git git@github.com:project-draco-hr/zeppelin.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/google/binnavi.git git@github.com:project-draco-hr/binnavi.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/grails/grails-core.git git@github.com:project-draco-hr/grails-core.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/Wizcorp/phonegap-facebook-plugin.git git@github.com:project-draco-hr/phonegap-facebook-plugin.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/owncloud/android.git git@github.com:project-draco-hr/android.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/cymcsg/UltimateAndroid.git git@github.com:project-draco-hr/UltimateAndroid.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/apereo/cas.git git@github.com:project-draco-hr/cas.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/voldemort/voldemort.git git@github.com:project-draco-hr/voldemort.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/hazelcast/hazelcast.git git@github.com:project-draco-hr/hazelcast.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/wildfly/wildfly.git git@github.com:project-draco-hr/wildfly.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/bigbluebutton/bigbluebutton.git git@github.com:project-draco-hr/bigbluebutton.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/xcltapestry/XCL-Charts.git git@github.com:project-draco-hr/XCL-Charts.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/MovingBlocks/Terasology.git git@github.com:project-draco-hr/Terasology.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/robovm/robovm.git git@github.com:project-draco-hr/robovm.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/gephi/gephi.git git@github.com:project-draco-hr/gephi.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/zaproxy/zaproxy.git git@github.com:project-draco-hr/zaproxy.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/apache/flink.git git@github.com:project-draco-hr/flink.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/aws/aws-sdk-java.git git@github.com:project-draco-hr/aws-sdk-java.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/MinecraftForge/MinecraftForge.git git@github.com:project-draco-hr/MinecraftForge.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/eishay/jvm-serializers.git git@github.com:project-draco-hr/jvm-serializers.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/konifar/android-material-design-icon-generator-plugin.git git@github.com:project-draco-hr/android-material-design-icon-generator-plugin.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/groovy/groovy-core.git git@github.com:project-draco-hr/groovy-core.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/danylovolokh/VideoPlayerManager.git git@github.com:project-draco-hr/VideoPlayerManager.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/lawloretienne/QuickReturn.git git@github.com:project-draco-hr/QuickReturn.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/apache/groovy.git git@github.com:project-draco-hr/groovy.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/jOOQ/jOOQ.git git@github.com:project-draco-hr/jOOQ.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/linkedin/pinot.git git@github.com:project-draco-hr/pinot.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/h2oai/h2o-3.git git@github.com:project-draco-hr/h2o-3.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/brianfrankcooper/YCSB.git git@github.com:project-draco-hr/YCSB.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/Konloch/bytecode-viewer.git git@github.com:project-draco-hr/bytecode-viewer.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/SonarSource/sonarqube.git git@github.com:project-draco-hr/sonarqube.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/wordpress-mobile/WordPress-Android.git git@github.com:project-draco-hr/WordPress-Android.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/xamarin/XobotOS.git git@github.com:project-draco-hr/XobotOS.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/killbill/killbill.git git@github.com:project-draco-hr/killbill.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/twitter/commons.git git@github.com:project-draco-hr/commons.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/jMonkeyEngine/jmonkeyengine.git git@github.com:project-draco-hr/jmonkeyengine.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/geometer/FBReaderJ.git git@github.com:project-draco-hr/FBReaderJ.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/raphw/byte-buddy.git git@github.com:project-draco-hr/byte-buddy.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/UweTrottmann/SeriesGuide.git git@github.com:project-draco-hr/SeriesGuide.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/jitsi/jitsi.git git@github.com:project-draco-hr/jitsi.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/apache/hive.git git@github.com:project-draco-hr/hive.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/pcpratts/rootbeer1.git git@github.com:project-draco-hr/rootbeer1.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/eclipse/jetty.project.git git@github.com:project-draco-hr/jetty.project.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/liquibase/liquibase.git git@github.com:project-draco-hr/liquibase.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/graphhopper/graphhopper.git git@github.com:project-draco-hr/graphhopper.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/serge-rider/dbeaver.git git@github.com:project-draco-hr/dbeaver.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/TwidereProject/Twidere-Android.git git@github.com:project-draco-hr/Twidere-Android.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/apache/camel.git git@github.com:project-draco-hr/camel.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/CrawlScript/WebCollector.git git@github.com:project-draco-hr/WebCollector.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/liferay/liferay-portal.git git@github.com:project-draco-hr/liferay-portal.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/moagrius/TileView.git git@github.com:project-draco-hr/TileView.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/igniterealtime/Openfire.git git@github.com:project-draco-hr/Openfire.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/osmandapp/Osmand.git git@github.com:project-draco-hr/Osmand.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/opentripplanner/OpenTripPlanner.git git@github.com:project-draco-hr/OpenTripPlanner.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/languagetool-org/languagetool.git git@github.com:project-draco-hr/languagetool.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/card-io/card.io-Android-SDK.git git@github.com:project-draco-hr/card.io-Android-SDK.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/alibaba/mdrill.git git@github.com:project-draco-hr/mdrill.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/apache/hbase.git git@github.com:project-draco-hr/hbase.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/VoltDB/voltdb.git git@github.com:project-draco-hr/voltdb.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/apache/nutch.git git@github.com:project-draco-hr/nutch.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/MizzleDK/Mizuu.git git@github.com:project-draco-hr/Mizuu.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/BroadleafCommerce/BroadleafCommerce.git git@github.com:project-draco-hr/BroadleafCommerce.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/android-cn/android-open-project-demo.git git@github.com:project-draco-hr/android-open-project-demo.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/lopspower/CircularFillableLoaders.git git@github.com:project-draco-hr/CircularFillableLoaders.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/jeeeyul/eclipse-themes.git git@github.com:project-draco-hr/eclipse-themes.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/fabric8io/fabric8.git git@github.com:project-draco-hr/fabric8.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/vaadin/vaadin.git git@github.com:project-draco-hr/vaadin.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/linkedin/gobblin.git git@github.com:project-draco-hr/gobblin.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/JetBrains/MPS.git git@github.com:project-draco-hr/MPS.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/cgeo/cgeo.git git@github.com:project-draco-hr/cgeo.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/gwtproject/gwt.git git@github.com:project-draco-hr/gwt.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/pentaho/pentaho-kettle.git git@github.com:project-draco-hr/pentaho-kettle.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/playgameservices/android-basic-samples.git git@github.com:project-draco-hr/android-basic-samples.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/droolsjbpm/drools.git git@github.com:project-draco-hr/drools.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/keycloak/keycloak.git git@github.com:project-draco-hr/keycloak.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/deeplearning4j/nd4j.git git@github.com:project-draco-hr/nd4j.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/FudanNLP/fnlp.git git@github.com:project-draco-hr/fnlp.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/OpenHFT/Chronicle-Map.git git@github.com:project-draco-hr/Chronicle-Map.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/apache/usergrid.git git@github.com:project-draco-hr/usergrid.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/winterDroid/android-drawable-importer-intellij-plugin.git git@github.com:project-draco-hr/android-drawable-importer-intellij-plugin.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/ankidroid/Anki-Android.git git@github.com:project-draco-hr/Anki-Android.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/geoserver/geoserver.git git@github.com:project-draco-hr/geoserver.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/seven332/EhViewer.git git@github.com:project-draco-hr/EhViewer.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/apache/incubator-geode.git git@github.com:project-draco-hr/incubator-geode.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/zhaoqp2010/andbase.git git@github.com:project-draco-hr/andbase.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/apache/kylin.git git@github.com:project-draco-hr/kylin.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/apache/jmeter.git git@github.com:project-draco-hr/jmeter.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/GoClipse/goclipse.git git@github.com:project-draco-hr/goclipse.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/RaiMan/SikuliX-2014.git git@github.com:project-draco-hr/SikuliX-2014.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/danikula/AndroidVideoCache.git git@github.com:project-draco-hr/AndroidVideoCache.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/apache/ignite.git git@github.com:project-draco-hr/ignite.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/plutext/docx4j.git git@github.com:project-draco-hr/docx4j.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/ccrama/Slide.git git@github.com:project-draco-hr/Slide.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/caoxinyu/RedisClient.git git@github.com:project-draco-hr/RedisClient.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/cmusphinx/sphinx4.git git@github.com:project-draco-hr/sphinx4.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/droolsjbpm/optaplanner.git git@github.com:project-draco-hr/optaplanner.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/forcedotcom/phoenix.git git@github.com:project-draco-hr/phoenix.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/Sable/soot.git git@github.com:project-draco-hr/soot.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/applidium/PokemonGo_Android_RE.git git@github.com:project-draco-hr/PokemonGo_Android_RE.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/KylinOLAP/Kylin.git git@github.com:project-draco-hr/Kylin.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/JetBrains/intellij-plugins.git git@github.com:project-draco-hr/intellij-plugins.git && \
docker run --rm -v $HOME/.ssh:/root/.ssh kenja converter.sh https://github.com/essentials/Essentials.git git@github.com:project-draco-hr/Essentials.git && \
